#!/usr/bin/env bash

# Temporary solution
# TODO: Make this better

avrdude -c stk500v2 -P /dev/cu.usbmodem00161782 -p atmega328p # sanity check
if [ $? -eq 0 ]; then
    avrdude -c stk500v2 -P /dev/cu.usbmodem00161782 -p atmega328p -U flash:w:main.hex
fi
